{{- if .Values.caCertificates}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-ca-certificates
  namespace: {{ include "h2ogpt.namespace" . | quote }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
  root-ca-bundle.crt:  |
    {{ .Values.caCertificates | nindent 4 | trim }}
{{- end }}